# Generated by Django 5.2.5 on 2025-08-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
