# Generated by Django 5.2.5 on 2025-09-02 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0002_eveningreport_morningreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=255)),
                ('work_type', models.CharField(choices=[('Client', 'Client'), ('Company', 'Company'), ('Other', 'Other')], max_length=50)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='uploads/files/')),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('color_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('content_example', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_works', to='monitoringapp.user')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_works', to='monitoringapp.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoringapp.department')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoringapp.team')),
            ],
        ),
    ]
