# Generated by Django 5.2.5 on 2025-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0003_projectassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassign',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
