# Generated by Django 5.2.5 on 2025-08-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='department_name',
        ),
    ]
