# Generated by Django 5.2.5 on 2025-08-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
