# Generated by Django 5.2.5 on 2025-08-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(max_length=100)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('work_location', models.CharField(blank=True, max_length=150, null=True)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
        ),
    ]
