# Generated by Django 5.2.5 on 2025-09-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0007_notepad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notepad',
        ),
    ]
