# Generated by Django 5.2.5 on 2025-08-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
