# Generated by Django 5.2.5 on 2025-08-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0010_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
