# Generated by Django 5.2.5 on 2025-09-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0020_knowledge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Knowledge',
        ),
    ]
