# Generated by Django 5.2.5 on 2025-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0024_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='knowledge_files/'),
        ),
    ]
