# Generated by Django 5.2.5 on 2025-09-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0025_alter_knowledge_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morningreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='EveningReport',
        ),
        migrations.DeleteModel(
            name='MorningReport',
        ),
    ]
