# Generated by Django 5.2.5 on 2025-09-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0029_user_last_login_time_user_last_logout_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_logout_time',
        ),
    ]
