# Generated by Django 5.2.5 on 2025-09-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0033_projectfile_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassign',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
