# Generated by Django 5.1.1 on 2025-07-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
