# Generated by Django 5.1.1 on 2025-07-25 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateField()),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='adminapp.user')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='adminapp.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.department')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.team')),
            ],
        ),
    ]
