# Generated by Django 5.2 on 2025-08-16 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_team_department_alter_assignedproject_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='department',
        ),
        migrations.AlterField(
            model_name='assignedproject',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='adminapp.user'),
        ),
        migrations.AlterField(
            model_name='assignedproject',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='adminapp.user'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
