# Generated by Django 5.2 on 2025-08-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_team_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedProject',
        ),
    ]
